import express from "express";
import cors from "cors";
import http from "http";
import WebSocket, { WebSocketServer } from "ws";
import { authenticator } from "otplib";
import webpush from "web-push";

const PORT = Number(process.env.PORT || 10000);
const CLIENT_ID = String(process.env.DHAN_CLIENT_ID || "").trim();
const PIN = String(process.env.DHAN_PIN || "").trim();
const TOTP_SECRET = String(process.env.DHAN_TOTP_SECRET || "").replace(/\s+/g, "").toUpperCase();
const STATIC_TOKEN = String(process.env.DHAN_ACCESS_TOKEN || "").trim();
const VAPID_PUBLIC_KEY = String(process.env.VAPID_PUBLIC_KEY || "").trim();
const VAPID_PRIVATE_KEY = String(process.env.VAPID_PRIVATE_KEY || "").trim();
const VAPID_SUBJECT = String(process.env.VAPID_SUBJECT || "mailto:alerts@example.com").trim();
if (VAPID_PUBLIC_KEY && VAPID_PRIVATE_KEY) webpush.setVapidDetails(VAPID_SUBJECT, VAPID_PUBLIC_KEY, VAPID_PRIVATE_KEY);

const app = express();
app.use(cors({ origin: true }));
app.use(express.json({ limit: "2mb" }));
app.use((req,res,next)=>{res.setHeader("Cache-Control","no-store, no-cache, must-revalidate, proxy-revalidate");res.setHeader("Pragma","no-cache");res.setHeader("Expires","0");next();});

const INDEXES = {
  NIFTY:{securityId:"13",segment:"IDX_I",feedSegment:"IDX_I",name:"NIFTY",step:50},
  BANKNIFTY:{securityId:"25",segment:"IDX_I",feedSegment:"IDX_I",name:"BANKNIFTY",step:100},
  FINNIFTY:{securityId:"27",segment:"IDX_I",feedSegment:"IDX_I",name:"FINNIFTY",step:50},
  MIDCPNIFTY:{securityId:"442",segment:"IDX_I",feedSegment:"IDX_I",name:"MIDCPNIFTY",step:25},
  SENSEX:{securityId:"51",segment:"IDX_I",feedSegment:"IDX_I",name:"SENSEX",step:100}
};
const state={version:"6.0-DATA-PROVIDER",indexKey:String(process.env.DEFAULT_INDEX||"NIFTY").toUpperCase(),expiry:null,spot:null,dhanConnected:false,depthConnected:false,lastTick:null,marketStatus:null,chain:{updatedAt:null,expiry:null,rows:[],atm:null,maxPain:null},analytics:null,subscriptions:[],server:{startedAt:Date.now(),ticks:0,packets:0,reconnects:0}};
const clients=new Set(),pushSubscriptions=new Map(),ticks=new Map(),candles=new Map(),instruments=new Map(),optionMeta=new Map();
let dhanWs=null,depthWs=null,reconnectTimer=null,depthReconnectTimer=null,chainTimer=null,instrumentRefreshTimer=null,accessToken=STATIC_TOKEN,tokenExpiry=0,authStatus=STATIC_TOKEN?"STATIC_TOKEN":"WAITING",authLastError=null,authLastSuccessAt=null,chainBusy=false;
const now=()=>Date.now(),key=(s,i)=>`${s}:${i}`,safeNum=(v,f=null)=>Number.isFinite(Number(v))?Number(v):f;
function log(...a){console.log(new Date().toISOString(),...a)}
function broadcast(m){const s=JSON.stringify(m);for(const ws of clients)if(ws.readyState===WebSocket.OPEN)ws.send(s)}
function publicState(){return {...state}}
function underlyingInfo(){return INDEXES[state.indexKey]||INDEXES.NIFTY}

async function getAccessToken(){
  if(STATIC_TOKEN){authStatus="STATIC_TOKEN";return STATIC_TOKEN}
  if(!CLIENT_ID||!PIN||!TOTP_SECRET){authStatus="CONFIG_ERROR";throw Error("Set DHAN_CLIENT_ID, DHAN_PIN and DHAN_TOTP_SECRET or DHAN_ACCESS_TOKEN")}
  if(accessToken&&now()<tokenExpiry-60000)return accessToken;
  const totp=authenticator.generate(TOTP_SECRET);
  const url=`https://auth.dhan.co/app/generateAccessToken?dhanClientId=${encodeURIComponent(CLIENT_ID)}&pin=${encodeURIComponent(PIN)}&totp=${encodeURIComponent(totp)}`;
  const r=await fetch(url,{method:"POST",headers:{Accept:"application/json","Content-Type":"application/json"}});
  const text=await r.text();let j;try{j=JSON.parse(text)}catch{throw Error(`Dhan auth returned non-JSON: ${text.slice(0,200)}`)}
  if(!r.ok||!j.accessToken){authStatus=`FAILED_${r.status}`;authLastError=j.errorMessage||j.message||text.slice(0,200);throw Error(`Dhan auth failed ${r.status}: ${authLastError}`)}
  accessToken=j.accessToken;authStatus="AUTHENTICATED";authLastError=null;authLastSuccessAt=now();tokenExpiry=j.expiryTime?new Date(j.expiryTime).getTime():now()+23*3600000;return accessToken;
}
async function dhanPost(path,body){const token=await getAccessToken();const headers={"Content-Type":"application/json",Accept:"application/json","access-token":token};if(CLIENT_ID)headers["client-id"]=CLIENT_ID;const r=await fetch(`https://api.dhan.co/v2${path}`,{method:"POST",headers,body:JSON.stringify(body)});const text=await r.text();let j;try{j=JSON.parse(text)}catch{j={raw:text}}if(!r.ok)throw Error(`Dhan ${r.status}: ${text.slice(0,400)}`);return j}
async function loadInstrumentMaster(){
  const r=await fetch("https://images.dhan.co/api-data/api-scrip-master.csv");if(!r.ok)throw Error(`Instrument master ${r.status}`);const text=await r.text();const lines=text.split(/\r?\n/).filter(Boolean);const parse=line=>{const o=[];let c="",q=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'){if(q&&line[i+1]==='"'){c+='"';i++}else q=!q}else if(ch===','&&!q){o.push(c);c=""}else c+=ch}o.push(c);return o};const h=parse(lines[0]).map(x=>x.trim()),idx=n=>h.indexOf(n);const ix={exch:idx("SEM_EXM_EXCH_ID"),seg:idx("SEM_SEGMENT"),id:idx("SEM_SMST_SECURITY_ID"),inst:idx("SEM_INSTRUMENT_NAME"),expiry:idx("SEM_EXPIRY_DATE"),strike:idx("SEM_STRIKE_PRICE"),opt:idx("SEM_OPTION_TYPE"),trading:idx("SEM_TRADING_SYMBOL"),custom:idx("SEM_CUSTOM_SYMBOL"),lot:idx("SEM_LOT_UNITS"),symbol:idx("SM_SYMBOL_NAME"),tick:idx("SEM_TICK_SIZE")};const map={"NSE:I":"IDX_I","NSE:D":"NSE_FNO","NSE:E":"NSE_EQ","BSE:I":"BSE_IDX","BSE:D":"BSE_FNO","BSE:E":"BSE_EQ","MCX:M":"MCX_COMM"};instruments.clear();for(let i=1;i<lines.length;i++){const c=parse(lines[i]);if(c.length<8)continue;const es=map[`${c[ix.exch]}:${c[ix.seg]}`],id=c[ix.id];if(!es||!id)continue;instruments.set(key(es,id),{securityId:String(id),exchangeSegment:es,exchange:c[ix.exch],segmentCode:c[ix.seg],instrument:c[ix.inst]||null,expiry:c[ix.expiry]||null,strike:safeNum(c[ix.strike],0),optionType:c[ix.opt]||null,tradingSymbol:c[ix.trading]||null,customSymbol:c[ix.custom]||null,symbol:c[ix.symbol]||null,lotSize:safeNum(c[ix.lot],1),tickSize:safeNum(c[ix.tick],null)})}log(`Loaded ${instruments.size} Dhan instruments`)
}
async function getExpiryList(){const x=underlyingInfo();const j=await dhanPost("/optionchain/expirylist",{UnderlyingScrip:Number(x.securityId),UnderlyingSeg:x.segment});const dates=Array.isArray(j.data)?j.data:[];if(dates.length&&(!state.expiry||!dates.includes(state.expiry)))state.expiry=dates[0];return dates}
async function getOptionChain(){const x=underlyingInfo();return dhanPost("/optionchain",{UnderlyingScrip:Number(x.securityId),UnderlyingSeg:x.segment,Expiry:state.expiry})}
function bsTime(expiry){return Math.max((new Date(expiry).getTime()-now())/86400000/365,1/(365*24*60))}
function erf(x){const sign=x<0?-1:1;x=Math.abs(x);const a1=.254829592,a2=-.284496736,a3=1.421413741,a4=-1.453152027,a5=1.061405429,p=.3275911,t=1/(1+p*x);return sign*(1-(((((a5*t+a4)*t)+a3)*t+a2)*t+a1)*t*Math.exp(-x*x))}
function normPdf(x){return Math.exp(-.5*x*x)/Math.sqrt(2*Math.PI)}function normCdf(x){return .5*(1+erf(x/Math.sqrt(2)))}
function hiddenGreeks({spot,strike,iv,expiry,type}){const S=Number(spot),K=Number(strike),sigma=Math.max(Number(iv)/100,.0001),T=bsTime(expiry);if(!(S>0&&K>0))return{};const call=type==="CE",r=.06,d1=(Math.log(S/K)+(r+sigma*sigma/2)*T)/(sigma*Math.sqrt(T)),d2=d1-sigma*Math.sqrt(T),pdf=normPdf(d1),gamma=pdf/(S*sigma*Math.sqrt(T)),vega=S*pdf*Math.sqrt(T)/100,delta=call?normCdf(d1):normCdf(d1)-1,theta=(-S*pdf*sigma/(2*Math.sqrt(T))-(call?r*K*Math.exp(-r*T)*normCdf(d2):-r*K*Math.exp(-r*T)*normCdf(-d2)))/365,vanna=-pdf*d2/sigma/100,vomma=vega*d1*d2/sigma;return{delta,gamma,vega,theta,vanna,vomma}}
function optionRow(strike,leg,type){if(!leg)return null;const ltp=safeNum(leg.last_price,0),oi=safeNum(leg.oi,0),vol=safeNum(leg.volume,0),prevOI=safeNum(leg.previous_oi,0),prevVol=safeNum(leg.previous_volume,0),iv=safeNum(leg.implied_volatility,0),g=hiddenGreeks({spot:state.spot,strike,iv,expiry:state.expiry,type}),lot=safeNum(instruments.get(key("NSE_FNO",leg.security_id))?.lotSize,1),gex=(g.gamma||safeNum(leg.greeks?.gamma,0))*oi*lot*(state.spot||0)*(state.spot||0)/1e7;return{strike,type,securityId:String(leg.security_id),tradingSymbol:instruments.get(key("NSE_FNO",leg.security_id))?.tradingSymbol||null,ltp,oi,previousOI:prevOI,changeOI:oi-prevOI,volume:vol,previousVolume:prevVol,changeVolume:vol-prevVol,iv,bid:safeNum(leg.top_bid_price,0),ask:safeNum(leg.top_ask_price,0),bidQty:safeNum(leg.top_bid_quantity,0),askQty:safeNum(leg.top_ask_quantity,0),averagePrice:safeNum(leg.average_price,0),hiddenGreeks:g,gexProxy:Number(gex.toFixed(3)),notionalOI:Number((oi*lot*strike).toFixed(2))}}
function buildAnalytics(rows,spot){const ce=rows.filter(x=>x.type==="CE"),pe=rows.filter(x=>x.type==="PE"),sum=(a,k)=>a.reduce((s,x)=>s+(Number(x[k])||0),0),callOI=sum(ce,"oi"),putOI=sum(pe,"oi"),callVol=sum(ce,"volume"),putVol=sum(pe,"volume"),callCh=sum(ce,"changeOI"),putCh=sum(pe,"changeOI"),pcr=callOI?putOI/callOI:null,pcrVol=callVol?putVol/callVol:null,callWall=ce.reduce((a,b)=>!a||b.oi>a.oi?b:a,null),putWall=pe.reduce((a,b)=>!a||b.oi>a.oi?b:a,null),atm=rows.reduce((a,b)=>!a||Math.abs(b.strike-spot)<Math.abs(a.strike-spot)?b:a,null)?.strike||null,strikes=[...new Set(rows.map(x=>x.strike))].sort((a,b)=>a-b);let maxPain=null,min=Infinity;for(const k of strikes){let p=0;for(const x of ce)p+=Math.max(0,k-x.strike)*x.oi;for(const x of pe)p+=Math.max(0,x.strike-k)*x.oi;if(p<min){min=p;maxPain=k}}const gexCE=sum(ce,"gexProxy"),gexPE=sum(pe,"gexProxy"),gex=gexCE-gexPE,atmRows=rows.filter(x=>x.strike===atm),atmIV=atmRows.length?atmRows.reduce((s,x)=>s+(x.iv||0),0)/atmRows.length:0;return{atm,pcr,pcrVolume,callOI,putOI,callChangeOI:callCh,putChangeOI:putCh,callVolume:callVol,putVolume:putVol,callChangeVolume:sum(ce,"changeVolume"),putChangeVolume:sum(pe,"changeVolume"),callOIWall:callWall?.strike??null,putOIWall:putWall?.strike??null,maxPain,maxPainValue:min===Infinity?null:min,atmIV:Number(atmIV.toFixed(3)),totalGEXProxy:Number(gex.toFixed(3)),callGEXProxy:Number(gexCE.toFixed(3)),putGEXProxy:Number(gexPE.toFixed(3)),dealerHedgePressureProxy:Number((-gex).toFixed(3)),interpretation:gex>0?"positive-gamma proxy":gex<0?"negative-gamma proxy":"neutral",at:now()}}
function nearRows(rows,spot,n=5){return [...new Map(rows.map(x=>[x.strike,x])).values()].sort((a,b)=>Math.abs(a.strike-spot)-Math.abs(b.strike-spot)).slice(0,n*2)}
function updateCandle(k,t){if(!t.ltp)return;const tf=60000,tm=Math.floor((t.ltt||now())/tf)*tf;let a=candles.get(k)||[],c=a[a.length-1];if(!c||c.time!==tm){c={time:tm,open:t.ltp,high:t.ltp,low:t.ltp,close:t.ltp,volume:t.volume??0};a=[...a,c]}else{c.high=Math.max(c.high,t.ltp);c.low=Math.min(c.low,t.ltp);c.close=t.ltp;c.volume=t.volume??c.volume}if(a.length>1500)a=a.slice(-1500);candles.set(k,a)}
function updateTick(p){if(p.sec==null)return;const seg=p.segName||p.segment||p.seg,k=key(seg,p.sec),t=ticks.get(k)||{securityId:String(p.sec),exchangeSegment:seg};Object.assign(t,{updatedAt:now()});for(const n of ["ltp","avgPrice","volume","sellQty","buyQty","open","close","high","low","oi","oiDayHigh","oiDayLow","prevClose","prevOI","lastTradeQty","ltt"])if(p[n]!=null)t[n]=p[n];if(p.depth)t.depth=p.depth;if(p.depth20)t.depth20=p.depth20;t.changeVolume=t.volume!=null&&t.sessionStartVolume!=null?t.volume-t.sessionStartVolume:0;if(t.sessionStartVolume==null&&t.volume!=null)t.sessionStartVolume=t.volume;if(t.oi!=null&&t.sessionStartOI==null)t.sessionStartOI=t.oi;if(t.oi!=null&&t.sessionStartOI!=null)t.changeOI=t.oi-t.sessionStartOI;if(p.prevOI!=null)t.changeOI=t.oi!=null?t.oi-p.prevOI:t.changeOI;ticks.set(k,t);state.server.ticks++;state.lastTick={securityId:String(p.sec),exchangeSegment:seg,ltp:t.ltp,ltt:t.ltt,at:now()};if(seg===underlyingInfo().feedSegment&&String(p.sec)===underlyingInfo().securityId){state.spot=p.ltp??state.spot;state.marketStatus=p.marketStatus??state.marketStatus}const meta=optionMeta.get(k);if(meta)Object.assign(meta,{ltp:t.ltp,volume:t.volume,changeVolume:t.changeVolume,oi:t.oi,changeOI:t.changeOI,bid:t.bid??meta.bid,ask:t.ask??meta.ask,bidQty:t.bidQty??meta.bidQty,askQty:t.askQty??meta.askQty});updateCandle(k,t);broadcast({type:"tick",tick:t})}
function parseFeedPacket(buf){if(buf.length<8)return null;const dv=new DataView(buf.buffer,buf.byteOffset,buf.byteLength),code=dv.getUint8(0),len=dv.getUint16(1,true)||buf.length,segByte=dv.getUint8(3),sec=dv.getUint32(4,true),segName={0:"IDX_I",1:"NSE_EQ",2:"NSE_FNO",3:"NSE_CURRENCY",4:"BSE_EQ",5:"MCX_COMM",7:"BSE_CURRENCY",8:"BSE_FNO"}[segByte]||String(segByte),f=o=>dv.getFloat32(o,true),i=o=>dv.getInt32(o,true),u16=o=>dv.getUint16(o,true);const base={code,len,seg:segByte,segName,sec};if(code===2&&buf.length>=16)return{...base,type:"ticker",ltp:f(8),ltt:i(12)*1000};if(code===4&&buf.length>=51)return{...base,type:"quote",ltp:f(8),ltq:u16(12),ltt:i(14)*1000,avgPrice:f(18),volume:i(22),sellQty:i(26),buyQty:i(30),open:f(34),close:f(38),high:f(42),low:f(46)};if(code===5&&buf.length>=12)return{...base,type:"oi",oi:i(8)};if(code===6&&buf.length>=16)return{...base,type:"prev",prevClose:f(8),prevOI:i(12)};if(code===7)return{...base,type:"marketStatus",marketStatus:buf.length>=10?u16(8):null};if(code===8&&buf.length>=163){const depth=[];for(let n=0;n<5;n++){const o=63+n*20;depth.push({bidQty:i(o),askQty:i(o+4),bidOrders:dv.getInt16(o+8,true),askOrders:dv.getInt16(o+10,true),bid:f(o+12),ask:f(o+16)})}return{...base,type:"full",ltp:f(8),ltq:u16(12),ltt:i(14)*1000,avgPrice:f(18),volume:i(22),sellQty:i(26),buyQty:i(30),oi:i(34),oiDayHigh:i(38),oiDayLow:i(42),open:f(46),close:f(50),high:f(54),low:f(58),depth}}
if(code===50)return{...base,type:"disconnect"};return base}
function decodeFeed(data){const b=Buffer.from(data),out=[];let off=0;while(off+8<=b.length){const len=b.readUInt16LE(off+1)||b.length-off;if(len<8||off+len>b.length)break;const p=parseFeedPacket(b.subarray(off,off+len));if(p)out.push(p);off+=len}return out}
function parseDepthPacket(buf){if(buf.length<13)return null;const dv=new DataView(buf.buffer,buf.byteOffset,buf.byteLength),code=dv.getUint8(2),sec=dv.getUint32(4,true),len=dv.getUint16(0,true)||buf.length;if((code!==41&&code!==51)||len<333)return null;const side=code===41?"bids":"asks",rows=[];for(let n=0;n<20;n++){const o=12+n*16;const price=dv.getFloat64(o,true),qty=dv.getUint32(o+8,true),orders=dv.getUint32(o+12,true);rows.push({price,qty,orders})}return{code,sec,side,rows}}
function decodeDepth(data){const b=Buffer.from(data),out=[];let off=0;while(off+12<=b.length){const len=b.readUInt16LE(off)||b.length-off;if(len<13||off+len>b.length)break;const p=parseDepthPacket(b.subarray(off,off+len));if(p)out.push(p);off+=len}return out}
function applyDepth(p){const k=key("NSE_FNO",p.sec),t=ticks.get(k)||{securityId:String(p.sec),exchangeSegment:"NSE_FNO"};const d=t.depth20||{bids:[],asks:[],updatedAt:0};d[p.side]=p.rows;d.updatedAt=now();t.depth20=d;t.depth=t.depth||[{bid:p.side==="bids"?p.rows[0]?.price:undefined,ask:p.side==="asks"?p.rows[0]?.price:undefined,bidQty:p.side==="bids"?p.rows[0]?.qty:undefined,askQty:p.side==="asks"?p.rows[0]?.qty:undefined}];ticks.set(k,t);broadcast({type:"depth",securityId:String(p.sec),depth20:d})}
function subscribe(ws,list,requestCode=21){if(!ws||ws.readyState!==WebSocket.OPEN||!list.length)return;const unique=[...new Map(list.map(x=>[key(x.ExchangeSegment,x.SecurityId),x])).values()];for(let i=0;i<unique.length;i+=100){const a=unique.slice(i,i+100);ws.send(JSON.stringify({RequestCode:requestCode,InstrumentCount:a.length,InstrumentList:a}))}}
function syncDepth(rows){if(!depthWs||depthWs.readyState!==WebSocket.OPEN)return;const a=rows.slice(0,50).map(x=>({ExchangeSegment:"NSE_FNO",SecurityId:String(x.securityId)}));if(a.length)depthWs.send(JSON.stringify({RequestCode:23,InstrumentCount:a.length,InstrumentList:a}))}
function rowsWithLive(){return state.chain.rows.map(r=>{const t=ticks.get(key("NSE_FNO",r.securityId));return t?{...r,ltp:t.ltp,volume:t.volume,changeVolume:t.changeVolume,oi:t.oi,changeOI:t.changeOI,bid:t.depth20?.bids?.[0]?.price??r.bid,ask:t.depth20?.asks?.[0]?.price??r.ask,bidQty:t.depth20?.bids?.[0]?.qty??r.bidQty,askQty:t.depth20?.asks?.[0]?.qty??r.askQty,depth20:t.depth20}:r})}
async function refreshChain(){if(chainBusy)return;chainBusy=true;try{if(!state.expiry)await getExpiryList();const j=await getOptionChain();const spot=safeNum(j?.data?.last_price,state.spot);if(spot!=null)state.spot=spot;const oc=j?.data?.oc||{},rows=[];for(const [ks,row] of Object.entries(oc)){const strike=Number(ks);if(!Number.isFinite(strike))continue;const ce=optionRow(strike,row.ce,"CE"),pe=optionRow(strike,row.pe,"PE");if(ce){rows.push(ce);optionMeta.set(key("NSE_FNO",ce.securityId),ce)}if(pe){rows.push(pe);optionMeta.set(key("NSE_FNO",pe.securityId),pe)}}state.chain={updatedAt:now(),expiry:state.expiry,rows,atm:buildAnalytics(rows,state.spot).atm,maxPain:buildAnalytics(rows,state.spot).maxPain};state.analytics=buildAnalytics(rows,state.spot);const near=nearRows(rows,state.spot,10);state.subscriptions=[{ExchangeSegment:underlyingInfo().feedSegment,SecurityId:underlyingInfo().securityId},...near.map(x=>({ExchangeSegment:"NSE_FNO",SecurityId:x.securityId}))];subscribe(dhanWs,state.subscriptions,21);syncDepth(near);broadcast({type:"optionChain",chain:{...state.chain,rows:rowsWithLive()},analytics:state.analytics});broadcast({type:"state",state:publicState()})}catch(e){log("Option chain:",e.message);broadcast({type:"error",message:e.message})}finally{chainBusy=false}}
function connectFeed(){clearTimeout(reconnectTimer);try{dhanWs?.close()}catch{}getAccessToken().then(token=>{const url=`wss://api-feed.dhan.co?version=2&token=${encodeURIComponent(token)}&clientId=${encodeURIComponent(CLIENT_ID)}&authType=2`;dhanWs=new WebSocket(url);dhanWs.on("open",()=>{state.dhanConnected=true;state.server.reconnects++;broadcast({type:"state",state:publicState()});subscribe(dhanWs,state.subscriptions.length?state.subscriptions:[{ExchangeSegment:underlyingInfo().feedSegment,SecurityId:underlyingInfo().securityId}],21)});dhanWs.on("message",data=>{for(const p of decodeFeed(data)){state.server.packets++;updateTick(p)}});dhanWs.on("close",()=>{state.dhanConnected=false;broadcast({type:"state",state:publicState()});reconnectTimer=setTimeout(connectFeed,5000)});dhanWs.on("error",e=>log("Feed error",e.message))}).catch(e=>{authStatus=authStatus==="CONFIG_ERROR"?authStatus:"AUTH_FAILED";authLastError=e.message;state.dhanConnected=false;broadcast({type:"error",message:e.message});reconnectTimer=setTimeout(connectFeed,10000)})}
function connectDepth(){clearTimeout(depthReconnectTimer);try{depthWs?.close()}catch{}getAccessToken().then(token=>{depthWs=new WebSocket(`wss://depth-api-feed.dhan.co/twentydepth?token=${encodeURIComponent(token)}&clientId=${encodeURIComponent(CLIENT_ID)}&authType=2`);depthWs.on("open",()=>{state.depthConnected=true;broadcast({type:"state",state:publicState()});syncDepth(state.chain.rows)});depthWs.on("message",data=>{for(const p of decodeDepth(data))applyDepth(p)});depthWs.on("close",()=>{state.depthConnected=false;broadcast({type:"state",state:publicState()});depthReconnectTimer=setTimeout(connectDepth,7000)});depthWs.on("error",e=>log("Depth error",e.message))}).catch(e=>log("Depth auth",e.message))}

app.get("/",(_q,res)=>res.status(200).type("html").send(`<html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>SITARAM Data Provider</title><style>body{font-family:system-ui;background:#06111b;color:#eef;padding:30px}main{max-width:720px;margin:auto;background:#0a1b2a;padding:24px;border-radius:18px}code{background:#102638;padding:3px 6px;border-radius:6px}.ok{color:#31d6a5}</style></head><body><main><h1>SITARAM Data Provider V6</h1><p class="ok">● ONLINE</p><p>Data only. Entry/confluence logic lives in the PWA.</p><p>Dhan: <b id="d">checking</b> · L20: <b id="l">checking</b></p><p><a href="/api/health">/api/health</a> · <a href="/api/state">/api/state</a> · <a href="/api/option-chain">/api/option-chain</a> · <a href="/api/analytics">/api/analytics</a></p><script>setInterval(async()=>{try{let j=await fetch('/api/health').then(r=>r.json());d.textContent=j.dhanConnected?'CONNECTED':'WAITING';l.textContent=j.depthConnected?'CONNECTED':'WAITING'}catch{d.textContent='OFFLINE'}},1500)</script></main></body></html>`));
app.get("/api/health",(_q,res)=>res.json({ok:true,version:state.version,dhanConnected:state.dhanConnected,depthConnected:state.depthConnected,authStatus,authLastSuccessAt,authLastError,ticks:state.server.ticks,packets:state.server.packets,subscriptions:state.subscriptions.length,chainRows:state.chain.rows.length,spot:state.spot,time:now()}));
app.get("/api/config",(_q,res)=>res.json({ok:true,version:state.version,indexes:INDEXES,vapidPublicKey:VAPID_PUBLIC_KEY,features:["tick","quote","oi","volume","depth5","depth20","option-chain","greeks","hidden-greeks","oi-walls","pcr","max-pain","iv-smile","history","websocket"]}));
app.get("/api/state",(_q,res)=>res.json(publicState()));
app.get("/api/ticks",(_q,res)=>res.json({ok:true,data:[...ticks.values()]}));
app.get("/api/tick",(q,res)=>{const seg=String(q.query.segment||"NSE_FNO"),sec=String(q.query.securityId||""),t=ticks.get(key(seg,sec));res.json({ok:!!t,data:t||null})});
app.get("/api/history",(q,res)=>{const seg=String(q.query.segment||underlyingInfo().feedSegment),sec=String(q.query.securityId||underlyingInfo().securityId);res.json({ok:true,data:candles.get(key(seg,sec))||[]})});
app.get("/api/option-chain",(_q,res)=>res.json({ok:true,expiry:state.expiry,spot:state.spot,rows:rowsWithLive(),analytics:state.analytics,updatedAt:state.chain.updatedAt}));
app.get("/api/analytics",(_q,res)=>res.json({ok:true,spot:state.spot,analytics:state.analytics}));
app.get("/api/depth",(q,res)=>{const sec=String(q.query.securityId||""),t=ticks.get(key(String(q.query.segment||"NSE_FNO"),sec));res.json({ok:true,data:t?.depth20||{bids:[],asks:[],updatedAt:null}})});
app.get("/api/instruments",(q,res)=>{const search=String(q.query.search||"").toUpperCase(),limit=Math.min(Number(q.query.limit||100),1000),arr=[...instruments.values()].filter(x=>!search||JSON.stringify(x).toUpperCase().includes(search)).slice(0,limit);res.json({ok:true,count:arr.length,data:arr})});
app.post("/api/index",async(req,res)=>{const k=String(req.body?.index||"NIFTY").toUpperCase();if(!INDEXES[k])return res.status(400).json({ok:false,error:`Unknown index. Use ${Object.keys(INDEXES).join(", ")}`});state.indexKey=k;state.expiry=null;state.spot=null;state.chain={updatedAt:null,expiry:null,rows:[],atm:null,maxPain:null};state.analytics=null;state.subscriptions=[];await refreshChain();res.json({ok:true,state:publicState()})});
app.post("/api/expiry",async(_q,res)=>{try{const dates=await getExpiryList();res.json({ok:true,dates,selected:state.expiry})}catch(e){res.status(500).json({ok:false,error:e.message})}});
app.post("/api/expiry/select",async(req,res)=>{const x=String(req.body?.expiry||"");if(!x)return res.status(400).json({ok:false,error:"expiry required"});state.expiry=x;await refreshChain();res.json({ok:true,state:publicState()})});
app.post("/api/subscribe",(req,res)=>{const list=Array.isArray(req.body?.instruments)?req.body.instruments:[];subscribe(dhanWs,list.map(x=>({ExchangeSegment:String(x.ExchangeSegment||x.exchangeSegment),SecurityId:String(x.SecurityId||x.securityId)})).filter(x=>x.ExchangeSegment&&x.SecurityId),21);res.json({ok:true})});
app.post("/api/push/subscribe",(req,res)=>{const s=req.body;if(!s?.endpoint)return res.status(400).json({ok:false,error:"Invalid subscription"});pushSubscriptions.set(s.endpoint,s);res.json({ok:true})});
app.post("/api/push/test",async(_q,res)=>{let sent=0;for(const [k,s] of pushSubscriptions){try{await webpush.sendNotification(s,JSON.stringify({title:"SITARAM",body:"Backend transport is working."}));sent++}catch(e){if([404,410].includes(e.statusCode))pushSubscriptions.delete(k)}}res.json({ok:true,devices:pushSubscriptions.size,sent})});
const server=http.createServer(app),wss=new WebSocketServer({server,path:"/ws"});
wss.on("connection",ws=>{clients.add(ws);ws.send(JSON.stringify({type:"hello",version:state.version,features:["tick","quote","oi","volume","depth5","depth20","chain","analytics"]}));ws.send(JSON.stringify({type:"state",state:publicState()}));ws.on("close",()=>clients.delete(ws))});
async function boot(){try{await loadInstrumentMaster()}catch(e){log("Instrument master:",e.message)}try{await getExpiryList();await refreshChain()}catch(e){log("Chain startup:",e.message)}connectFeed();connectDepth();chainTimer=setInterval(refreshChain,4000);instrumentRefreshTimer=setInterval(()=>loadInstrumentMaster().catch(e=>log("Instrument refresh:",e.message)),6*3600000)}
server.listen(PORT,"0.0.0.0",()=>{log(`SITARAM Data Provider V6 listening on ${PORT}`);boot()});
